### ISSUE TITLE
"TypeError: this.listenTo is not a function" error occurs when executing the typedoc command

### ISSUE THREAD

**Issue by dogharrycatpotter** [DiFuks/typedoc-theme-hierarchy#30]
In the following condition

package.json
```zsh
    "typedoc": "0.26.0",
    "typedoc-plugin-markdown": "4.1.0",
```

typedoc.json
```json
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": [
    "./test/**/*.ts"
  ],
  "entryPointStrategy": "expand",
  "cleanOutputDir": true,
  "includeVersion": true,
  "lightHighlightTheme": "light-plus",
  "darkHighlightTheme": "dark-plus",
  "tsconfig": "./typedoc-tsconfig.json"
}

```

When I executed the command below, an error occurred. The error details are as shown in *1.
Do you know the cause?

```zsh
typedoc --plugin typedoc-theme-hierarchy --theme hierarchy --out ./docs
```

(*1) stack trace
```zsh
TypeDoc exiting with unexpected error:
TypeError: this.listenTo is not a function
    at new OverrideTheme (~/~/node_modules/typedoc-theme-hierarchy/dist/themes/OverrideTheme.js:14:14)
    at _classThis.prepareTheme (/~/~/node_modules/typedoc/dist/lib/output/renderer.js:323:34)
    at _classThis.render (~/~/node_modules/typedoc/dist/lib/output/renderer.js:252:23)
    at _classThis.generateDocs (~/~/nuxt3-saml/node_modules/typedoc/dist/lib/application.js:454:33)
    at run (~/~/node_modules/typedoc/dist/lib/cli.js:120:23)
    at async main (~/~/node_modules/typedoc/dist/lib/cli.js:49:26)
```

**Comment by DiFuks** [comment]
It seems there are issues with version 0.26. I'll be looking into it next week.
