### ISSUE TITLE
 Error: Cannot find module 'node:path'

### ISSUE THREAD

**Issue by pranaydutta89** [DiFuks/typedoc-theme-hierarchy#4]
it seems that latest version is using node api from v16, older version of nodejs are breaking up

```
Error: The plugin /Users/pranaydutta/Desktop/projects/ice/loc-mobi/node_modules/typedoc-theme-hierarchy/dist/index.js could not be loaded.
Info: Error: Cannot find module 'node:path'
Require stack:
- /Users/pranaydutta/Desktop/projects/ice/loc-mobi/node_modules/typedoc-theme-hierarchy/dist/themes/OverrideTheme.js
- /Users/pranaydutta/Desktop/projects/ice/loc-mobi/node_modules/typedoc-theme-hierarchy/dist/index.js
- /usr/local/lib/node_modules/typedoc/dist/lib/utils/plugins.js
- /usr/local/lib/node_modules/typedoc/dist/lib/utils/index.js
- /usr/local/lib/node_modules/typedoc/dist/lib/models/reflections/project.js
- /usr/local/lib/node_modules/typedoc/dist/lib/models/reflections/index.js
- /usr/local/lib/node_modules/typedoc/dist/lib/models/index.js
- /usr/local/lib/node_modules/typedoc/dist/lib/converter/context.js
- /usr/local/lib/node_modules/typedoc/dist/lib/converter/index.js
- /usr/local/lib/node_modules/typedoc/dist/lib/application.js
- /usr/local/lib/node_modules/typedoc/dist/index.js
- /usr/local/lib/node_modules/typedoc/bin/typedoc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/pranaydutta/Desktop/projects/ice/loc-mobi/node_modules/typedoc-theme-hierarchy/dist/themes/OverrideTheme.js:18:37)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

**Comment by DiFuks** [comment]
Really. I will fix

**Comment by pranaydutta89** [comment]
Thanks a ton @DiFuks , looking forward to use your theme once you fix it, really need for my project

**Comment by DiFuks** [comment]
@pranaydutta89 fixed
